// <auto-generated />
using System;
using BlazorTeste.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorTeste.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629122603_AddGroupBEntities")]
    partial class AddGroupBEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorTeste.Models.Advogado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessosAtivos")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Advogados");
                });

            modelBuilder.Entity("BlazorTeste.Models.Audiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvogadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAdvogado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Audiencias");
                });

            modelBuilder.Entity("BlazorTeste.Models.Campanha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Criador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destinatarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalDestinatarios")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campanhas");
                });

            modelBuilder.Entity("BlazorTeste.Models.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<int>("ContribuinteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Juros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LinhaDigitavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Multa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazaoSocialContribuinte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cobrancas");
                });

            modelBuilder.Entity("BlazorTeste.Models.ConfiguracaoEntidade", b =>
                {
                    b.Property<int>("EntidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntidadeId"));

                    b.HasKey("EntidadeId");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("BlazorTeste.Models.Contribuinte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapitalSocial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cnae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroFuncionarios")
                        .HasColumnType("int");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimeTributario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contribuintes");
                });

            modelBuilder.Entity("BlazorTeste.Models.Entidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CidadeSede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnaes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalContribuintes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("BlazorTeste.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipantes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaInscricao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalInscritos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("BlazorTeste.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("BlazorTeste.Models.GuiaSindical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContribuinteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Juros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LinhaDigitavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Multa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocialContribuinte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GuiaSindicais");
                });

            modelBuilder.Entity("BlazorTeste.Models.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaBancaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("NomeFornecedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Realizado")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LancamentosFinanceiros");
                });

            modelBuilder.Entity("BlazorTeste.Models.Negociacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContribuinteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DebitoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocialContribuinte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorNegociado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Negociacoes");
                });

            modelBuilder.Entity("BlazorTeste.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvogadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("NomeAdvogado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tribunal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("BlazorTeste.Models.RegistroBaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CobrancaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperadorResponsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocialContribuinte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoBaixa")
                        .HasColumnType("int");

                    b.Property<string>("TipoCobranca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RegistrosBaixa");
                });

            modelBuilder.Entity("BlazorTeste.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Formato")
                        .HasColumnType("int");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("BlazorTeste.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BlazorTeste.Models.ConfiguracaoEntidade", b =>
                {
                    b.OwnsOne("BlazorTeste.Models.ConfiguracaoBanco", "Banco", b1 =>
                        {
                            b1.Property<int>("ConfiguracaoEntidadeEntidadeId");

                            b1.Property<string>("Agencia")
                                .IsRequired();

                            b1.Property<string>("Banco")
                                .IsRequired();

                            b1.Property<string>("Carteira")
                                .IsRequired();

                            b1.Property<string>("Cedente")
                                .IsRequired();

                            b1.Property<string>("CodigoCedente")
                                .IsRequired();

                            b1.Property<string>("Conta")
                                .IsRequired();

                            b1.HasKey("ConfiguracaoEntidadeEntidadeId");

                            b1.ToTable("Configuracoes");

                            b1
                                .ToJson("Banco")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoEntidadeEntidadeId");
                        });

                    b.OwnsOne("BlazorTeste.Models.ConfiguracaoCobranca", "Cobranca", b1 =>
                        {
                            b1.Property<int>("ConfiguracaoEntidadeEntidadeId");

                            b1.Property<int>("DiaVencimento");

                            b1.Property<int>("DiasCarencia");

                            b1.Property<bool>("EmissaoAutomatica");

                            b1.Property<int>("EntidadeId");

                            b1.Property<decimal>("PercentualJurosDia");

                            b1.Property<decimal>("PercentualMulta");

                            b1.HasKey("ConfiguracaoEntidadeEntidadeId");

                            b1.ToTable("Configuracoes");

                            b1
                                .ToJson("Cobranca")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoEntidadeEntidadeId");

                            b1.OwnsMany("BlazorTeste.Models.FaixaCobranca", "Faixas", b2 =>
                                {
                                    b2.Property<int>("ConfiguracaoCobrancaConfiguracaoEntidadeEntidadeId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<decimal>("CapitalSocialMax");

                                    b2.Property<decimal>("CapitalSocialMin");

                                    b2.Property<string>("Descricao")
                                        .IsRequired();

                                    b2.Property<int>("Id");

                                    b2.Property<decimal>("PercentualCapital");

                                    b2.Property<decimal>("ValorFixo");

                                    b2.HasKey("ConfiguracaoCobrancaConfiguracaoEntidadeEntidadeId", "__synthesizedOrdinal");

                                    b2.ToTable("Configuracoes");

                                    b2.WithOwner()
                                        .HasForeignKey("ConfiguracaoCobrancaConfiguracaoEntidadeEntidadeId");
                                });

                            b1.Navigation("Faixas");
                        });

                    b.OwnsOne("BlazorTeste.Models.ConfiguracaoEmail", "Email", b1 =>
                        {
                            b1.Property<int>("ConfiguracaoEntidadeEntidadeId");

                            b1.Property<bool>("Ativo");

                            b1.Property<string>("EmailRemetente")
                                .IsRequired();

                            b1.Property<string>("NomeRemetente")
                                .IsRequired();

                            b1.Property<int>("Porta");

                            b1.Property<string>("ServidorSmtp")
                                .IsRequired();

                            b1.Property<bool>("UsarSsl");

                            b1.HasKey("ConfiguracaoEntidadeEntidadeId");

                            b1.ToTable("Configuracoes");

                            b1
                                .ToJson("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoEntidadeEntidadeId");
                        });

                    b.OwnsOne("BlazorTeste.Models.ConfiguracaoGeral", "Geral", b1 =>
                        {
                            b1.Property<int>("ConfiguracaoEntidadeEntidadeId");

                            b1.Property<string>("EmailContato")
                                .IsRequired();

                            b1.Property<string>("Endereco")
                                .IsRequired();

                            b1.Property<int>("EntidadeId");

                            b1.Property<string>("ResponsavelTecnico")
                                .IsRequired();

                            b1.Property<string>("Telefone")
                                .IsRequired();

                            b1.HasKey("ConfiguracaoEntidadeEntidadeId");

                            b1.ToTable("Configuracoes");

                            b1
                                .ToJson("Geral")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracaoEntidadeEntidadeId");
                        });

                    b.Navigation("Banco")
                        .IsRequired();

                    b.Navigation("Cobranca")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Geral")
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorTeste.Models.Contribuinte", b =>
                {
                    b.OwnsMany("BlazorTeste.Models.Contato", "Contatos", b1 =>
                        {
                            b1.Property<int>("ContribuinteId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContribuinteId", "Id");

                            b1.ToTable("Contatos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContribuinteId");
                        });

                    b.OwnsMany("BlazorTeste.Models.Endereco", "Enderecos", b1 =>
                        {
                            b1.Property<int>("ContribuinteId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContribuinteId", "Id");

                            b1.ToTable("Enderecos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContribuinteId");
                        });

                    b.OwnsMany("BlazorTeste.Models.HistoricoMensal", "Historico", b1 =>
                        {
                            b1.Property<int>("ContribuinteId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Ano")
                                .HasColumnType("int");

                            b1.Property<decimal>("CapitalSocial")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("Mes")
                                .HasColumnType("int");

                            b1.Property<int>("NumeroFuncionarios")
                                .HasColumnType("int");

                            b1.HasKey("ContribuinteId", "Id");

                            b1.ToTable("HistoricoMensais", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContribuinteId");
                        });

                    b.OwnsMany("BlazorTeste.Models.Socio", "Socios", b1 =>
                        {
                            b1.Property<int>("ContribuinteId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime?>("DataFim")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DataInicio")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Matricula")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("ValorMensalidade")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ContribuinteId", "Id");

                            b1.ToTable("Socios", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContribuinteId");
                        });

                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");

                    b.Navigation("Historico");

                    b.Navigation("Socios");
                });

            modelBuilder.Entity("BlazorTeste.Models.Evento", b =>
                {
                    b.OwnsMany("BlazorTeste.Models.InscricaoEvento", "Inscricoes", b1 =>
                        {
                            b1.Property<int>("EventoId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Cargo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("DataInscricao")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Empresa")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NomeParticipante")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Pago")
                                .HasColumnType("bit");

                            b1.Property<bool>("Presente")
                                .HasColumnType("bit");

                            b1.Property<string>("TipoHospedagem")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EventoId", "Id");

                            b1.ToTable("EventoInscricoes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("BlazorTeste.Models.Negociacao", b =>
                {
                    b.OwnsMany("BlazorTeste.Models.CobrancaOriginalNeg", "CobrancasOriginais", b1 =>
                        {
                            b1.Property<int>("NegociacaoId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AnoReferencia")
                                .HasColumnType("int");

                            b1.Property<decimal>("Juros")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Multa")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("ValorOriginal")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("NegociacaoId", "Id");

                            b1.ToTable("NegociacaoCobrancasOriginais", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NegociacaoId");
                        });

                    b.OwnsMany("BlazorTeste.Models.ParcelaNegociacao", "Parcelas", b1 =>
                        {
                            b1.Property<int>("NegociacaoId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime?>("DataPagamento")
                                .HasColumnType("datetime2");

                            b1.Property<string>("LinhaDigitavel")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.Property<bool>("Pago")
                                .HasColumnType("bit");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateTime>("Vencimento")
                                .HasColumnType("datetime2");

                            b1.HasKey("NegociacaoId", "Id");

                            b1.ToTable("NegociacaoParcelas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NegociacaoId");
                        });

                    b.Navigation("CobrancasOriginais");

                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
